name: Windows - LiteManager RDP

on:
  workflow_dispatch:

jobs:
  win-litemanager:
    runs-on: windows-latest

    steps:
    - name: Download and Install LiteManager Server
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://litemanager.com/soft/litemanager_free_server.msi" -OutFile "litemanager.msi"
        Start-Process msiexec.exe -ArgumentList '/i litemanager.msi /quiet' -Wait

    - name: Set LiteManager Password
      shell: powershell
      run: |
